# Generated by Django 3.2.12 on 2022-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectriciansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(default='-', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'electrician',
            },
        ),
        migrations.CreateModel(
            name='KipsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(default='-', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'kip',
            },
        ),
        migrations.CreateModel(
            name='LocksmithsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(default='-', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'locksmith',
            },
        ),
        migrations.CreateModel(
            name='MastersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(default='-', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='PaintAdjustersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(default='-', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'paint_adjuster',
            },
        ),
    ]
