# Generated by Django 3.2.12 on 2022-04-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_month', models.CharField(max_length=100, verbose_name='День месяца')),
                ('locksmith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation', to='shedule_sift.locksmithsmodel')),
                ('locksmith1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation1', to='shedule_sift.locksmithsmodel')),
                ('locksmith2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation2', to='shedule_sift.locksmithsmodel')),
                ('locksmith3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation3', to='shedule_sift.locksmithsmodel')),
                ('locksmith4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation4', to='shedule_sift.locksmithsmodel')),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
