# Generated by Django 3.2.12 on 2022-04-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0002_month1'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1',
            name='electrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation', to='shedule_sift.electriciansmodel'),
        ),
        migrations.AddField(
            model_name='month1',
            name='kip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kip_relation', to='shedule_sift.kipsmodel'),
        ),
        migrations.AddField(
            model_name='month1',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_relation', to='shedule_sift.mastersmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month1',
            name='paint_adjuster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paint_relation', to='shedule_sift.paintadjustersmodel'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation', to='shedule_sift.locksmithsmodel'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation1', to='shedule_sift.locksmithsmodel'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation2', to='shedule_sift.locksmithsmodel'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation3', to='shedule_sift.locksmithsmodel'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation4', to='shedule_sift.locksmithsmodel'),
        ),
    ]
