# Generated by Django 3.2.12 on 2022-04-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0003_auto_20220406_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='month1',
            name='electrician1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation1', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month1',
            name='electrician2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation2', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month1',
            name='electrician3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation3', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month1',
            name='electrician4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation4', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='electrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='kip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kip_relation', to='shedule_sift.kipsmodel', verbose_name='Киповец'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation1', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation2', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation3', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='locksmith4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation4', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_relation', to='shedule_sift.mastersmodel', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='month1',
            name='paint_adjuster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paint_relation', to='shedule_sift.paintadjustersmodel', verbose_name='Красковар'),
        ),
    ]
