# Generated by Django 3.2.12 on 2022-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0005_auto_20220406_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='day_month',
            field=models.SmallIntegerField(verbose_name='День месяца'),
        ),
    ]
