# Generated by Django 3.2.12 on 2022-04-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0006_alter_month_day_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='shift',
            field=models.SmallIntegerField(default=1, verbose_name='Смена'),
            preserve_default=False,
        ),
    ]
