# Generated by Django 3.2.12 on 2022-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0007_month_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название месяца')),
                ('numbr', models.SmallIntegerField(verbose_name='Номер месяца')),
            ],
            options={
                'db_table': 'NameMonth',
            },
        ),
    ]
