# Generated by Django 3.2.12 on 2022-04-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0008_namemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='electrician5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation5', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month',
            name='electrician6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation6', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month',
            name='locksmith5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation5', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AddField(
            model_name='month',
            name='locksmith6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation6', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
    ]
