# Generated by Django 3.2.12 on 2022-04-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_sift', '0009_auto_20220407_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='electrician7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation7', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month',
            name='electrician8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_relation8', to='shedule_sift.electriciansmodel', verbose_name='Электрик'),
        ),
        migrations.AddField(
            model_name='month',
            name='locksmith7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation7', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
        migrations.AddField(
            model_name='month',
            name='locksmith8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locksmith_relation8', to='shedule_sift.locksmithsmodel', verbose_name='Слесарь'),
        ),
    ]
